name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: update submodules
      run: git submodule update --init --recirsive
    - name: generate engine project
      run: python scripts/generate_engine_project.py
    - name: build engine project
      run: python scripts/build_engine.py
    - name: generate game project
      run: python scripts/generate_game_project.py
    - name: build game project
      run: python scripts/build_game.py
